### ISSUE TITLE
Sample tutorial

### ISSUE THREAD

**Issue by xiangyuan** [mob-sakai/UISystem#8]
do you have any sample tutorial?

**Comment by mob-sakai** [comment]
Oh, sorry.
It seems that I erased it by mistake...
I'll fix it in the next version.

**Comment by xiangyuan** [comment]
thanks man

**Comment by mob-sakai** [comment]
I committed the demo scene :)

However, I am planning to change UISystem significantly...

**Comment by xiangyuan** [comment]
@mob-sakai i will keep watching the repo. thanks for your update
